sudo: required
dist: trusty
language: cpp

compiler:
  - clang
  - gcc

env:
  - BUILD_TYPE=Debug
  - BUILD_TYPE=Release

before_install:
  - sudo apt-get -qq update

install:
  - sudo apt-get -qq build-dep pidgin
  - sudo apt-get -qq install pidgin-dev libpurple-dev cmake valgrind libcpputest-dev

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE="$BUILD_TYPE" ..
  - make
  - sh -c "if [ $BUILD_TYPE = Debug ]; then make test; fi"
  - sh -c "if [ $BUILD_TYPE = Debug ]; then G_SLICE=always-malloc valgrind --tool=memcheck --leak-check=yes --leak-resolution=high --num-callers=20 --track-fds=yes ./test/UnitTests; fi"
