language: cpp

compiler:
  - clang
  - gcc

before_install:
  - sudo apt-get -qq update

install:
  - sudo apt-get -qq build-dep pidgin
  - sudo apt-get -qq install pidgin-dev libpurple-dev cmake
  - wget http://weechat.org/files/tests/ubuntu/precise/amd64/libcpputest-dev_3.4-3_amd64.deb
  - sudo dpkg -i libcpputest-dev_3.4-3_amd64.deb

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug ..
  - make
  - make test
