language: cpp

compiler:
  - clang
  - gcc

env:
  - BUILD_TYPE=Debug
  - BUILD_TYPE=Release

before_install:
  - sudo apt-get -qq update

install:
  - sudo apt-get -qq build-dep pidgin
  - sudo apt-get -qq install pidgin-dev libpurple-dev cmake valgrind
  - wget http://weechat.org/files/tests/ubuntu/precise/amd64/libcpputest-dev_3.4-3_amd64.deb
  - sudo dpkg -i libcpputest-dev_3.4-3_amd64.deb

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE="$BUILD_TYPE" ..
  - make
  - make test
  - G_SLICE=always-malloc valgrind --tool=memcheck --leak-check=yes --leak-resolution=high --num-callers=20 --track-fds=yes ./test/UnitTests
